#  _  ___           _ _     _
# | |/ / |__  _   _(_) | __| |
# | ' /| '_ \| | | | | |/ _` |
# | . \| |_) | |_| | | | (_| |
# |_|\_\_.__/ \__,_|_|_|\__,_|
#
# NOTE: For more information on Kernel Module Kbuild files, see:
#	https://www.kernel.org/doc/html/v5.19/kbuild/makefiles.html#linux-kernel-makefiles
#
# Desc: Kbuild file defining the kernel module driver to be built

### Variables
XILINX_INCLUDE  := -I$$PWD../include -I$$PWD/include
## Special Config
# The flag "date-time" has been introduced in GCC 4.9.x series.
# But tests show that it was not present in 4.9.2.
# I set the limit to 4.9.4 but it may have to be set more accurately if problems are encountered.
GCCVERSION = $(shell gcc -dumpversion | sed -e 's/\.\([0-9][0-9]\)/\1/g' -e 's/\.\([0-9]\)/0\1/g' -e 's/^[0-9]\{3,4\}$$/&00/')
GCC49 := $(shell expr $(GCCVERSION) \>= 40904)


### Main final object name
obj-m := quantis-chip-pcie.o

### Include Header File
ccflags-y := -I$(src)/include

ifeq ($(GCC49),1)
	#CFLAGS_xdma-core.o += -Wno-error=date-time
	ccflags-y += -Wno-error=date-time
endif

### List's objects dependencies from the Main-obj
quantis-chip-pcie-y := idq-rng.o xdma-core.o xdma-sgm.o
